/* Inserting data into Airport cab vending machine through Adding Passengers -> Uber System -> Airport Cabs Vending Machine ->  */
DECLARE
    PROCEDURE_OUTPUT NUMBER;
    IS_VALID_OFFICER NUMBER;
BEGIN
    ADD_TO_PASSENGERS('B7492893', 777777777801, 'MOHAN GOWDA', 'IND', 'JVUE, BOSTON', 'YY9281O28', PROCEDURE_OUTPUT, IS_VALID_OFFICER);
END;

DECLARE
    PROCEDURE_OUTPUT NUMBER;
    IS_VALID_OFFICER NUMBER;
BEGIN
    ADD_TO_PASSENGERS('Y1872094', 777777777801, 'ROHIT PILLAI', 'IND', 'LONGWOOD, BOSTON', 'Y73829182', PROCEDURE_OUTPUT, IS_VALID_OFFICER);
END;

SELECT * FROM AIRPORT_TAXI_BOOKING_MACHINE;

CREATE VIEW AIRPORT_TAXI_BOOKING_MACHINE_VIEW AS SELECT * FROM AIRPORT_TAXI_BOOKING_MACHINE;

DROP TABLE AIRPORT_TAXI_BOOKING_MACHINE;

COMMIT;