/* Adding Customs Officer Data */

EXEC ADD_TO_CUSTOMS_OFFICERS('JOHN WESLEY');

EXEC ADD_TO_CUSTOMS_OFFICERS('PETER RUSSO');

EXEC ADD_TO_CUSTOMS_OFFICERS('Maria Garcia', INPUT_OFFICER_COUNTRY => 'UAE');

EXEC ADD_TO_CUSTOMS_OFFICERS('James Johnson', INPUT_OFFICER_COUNTRY => 'ENG');

EXEC ADD_TO_CUSTOMS_OFFICERS('James Smith', 'CAD');

EXEC ADD_TO_CUSTOMS_OFFICERS('BIANCO AJELLO');

/* Adding Passengers Data */

DECLARE
    PROCEDURE_OUTPUT NUMBER;
    IS_VALID_OFFICER NUMBER;
BEGIN
    ADD_TO_PASSENGERS('U1852134', 777777777777, 'STACY', 'ENG', 'RIVERWAY, BOSTON', 'I94333762', PROCEDURE_OUTPUT, IS_VALID_OFFICER);
END;

DECLARE
    PROCEDURE_OUTPUT NUMBER;
    IS_VALID_OFFICER NUMBER;
BEGIN
    ADD_TO_PASSENGERS('T1853125', 777777777789, 'PORT JANE', 'SPN', 'EVERGREEN, BOSTON', 'I94333763', PROCEDURE_OUTPUT, IS_VALID_OFFICER);
END;

DECLARE
    PROCEDURE_OUTPUT NUMBER;
    IS_VALID_OFFICER NUMBER;
BEGIN
    ADD_TO_PASSENGERS('E1852134', 777777777789, 'WADE SETH', 'FRA', 'BROOKLINE, BOSTON', 'I94333764', PROCEDURE_OUTPUT, IS_VALID_OFFICER);
END;

DECLARE
    PROCEDURE_OUTPUT NUMBER;
    IS_VALID_OFFICER NUMBER;
BEGIN
    ADD_TO_PASSENGERS('T1256167', 777777777801, 'RILEY JORGE', 'SAF', 'PLANE J., BOSTON', 'I94333765', PROCEDURE_OUTPUT, IS_VALID_OFFICER);
END;