/*
    Problem Statement: Create a table to store the cab id, cab number of a car and associate each cab with the registered driver in the Uber.
    Outline: We are making our data strong to assign a cab full fledged to the passenger we get in an airport.
*/
CREATE TABLE CAB_DETAILS 
(
    CAB_ID NUMBER(4) GENERATED ALWAYS as IDENTITY(START WITH 1111 INCREMENT BY 1),
    CAB_NUMBER VARCHAR2(8) UNIQUE NOT NULL,
    DRIVER_ID NUMBER(4) NOT NULL,
    DRIVER_NAME VARCHAR2(60) NOT NULL,
    CAB_SERVICE_NAME VARCHAR2(12) DEFAULT 'UBER' NOT NULL,
    DRIVER_RATING FLOAT NOT NULL,
    OPEN_TO_HIRE NUMBER(1) DEFAULT 1,
    CONSTRAINT PK_CAB_DETAILS PRIMARY KEY (CAB_ID),
    CONSTRAINT FK_CAB_DETAILS FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER_DETAILS (DRIVER_ID)
);

/* Procedure to add the details of cab and corresponding driver in the database */
CREATE OR REPLACE PROCEDURE ADD_CAB_TO_DATABASE 
(
    INPUT_CAB_NUMBER IN VARCHAR2,
    INPUT_DRIVER_ID IN NUMBER,
    IS_DRIVER_EXIST OUT NUMBER,
    CORRESPONDING_DRIVER_NAME OUT VARCHAR2,
    CORRESPONDING_DRIVER_RATING OUT FLOAT,
    INPUT_CAB_SERVICE_NAME IN VARCHAR2 DEFAULT 'UBER'
)
AS
BEGIN
    IS_DRIVER_EXIST := GET_DRIVER_EXISTENCE(INPUT_DRIVER_ID);
    CORRESPONDING_DRIVER_NAME := GET_DRIVER_NAME(INPUT_DRIVER_ID);
    CORRESPONDING_DRIVER_RATING := GET_DRIVER_RATING(INPUT_DRIVER_ID);
    IF IS_DRIVER_EXIST>0 THEN
        IF INPUT_CAB_SERVICE_NAME IN ('UBER') THEN
            INSERT INTO CAB_DETAILS (CAB_NUMBER, DRIVER_ID, DRIVER_NAME, DRIVER_RATING) 
            VALUES (INPUT_CAB_NUMBER, INPUT_DRIVER_ID, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING);
            DBMS_OUTPUT.PUT_LINE('CAB DETAILS INSERTED');
        ELSE
            INSERT INTO CAB_DETAILS (CAB_NUMBER, DRIVER_ID, CAB_SERVICE_NAME, DRIVER_NAME, DRIVER_RATING) 
            VALUES (INPUT_CAB_NUMBER, INPUT_DRIVER_ID, INPUT_CAB_SERVICE_NAME, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING);
            DBMS_OUTPUT.PUT_LINE('CAB DETAILS INSERTED');
        END IF;
    ELSE
        DBMS_OUTPUT.PUT_LINE('DRIVER DOES NOT EXIST SO CANNOT ENTER CAB DETAILS');
    END IF;
END;

/* Commiting the data */
COMMIT;