/* Dropping the tables to clear the data */
DROP TABLE CUSTOMS_OFFICERS;
DROP TABLE PASSENGERS_DATA;
DROP TABLE DRIVER_DETAILS;
DROP TABLE CAB_DETAILS;
DROP TABLE UBER_SERVICES;
DROP TABLE AIRPORT_TAXI_BOOKING_MACHINE;
DROP TABLE PAYMENT_DETAILS;

/* Customs => Tables = CUSTOMS_OFFICERS, PASSENGERS_DATA */

CREATE USER AIRPORT_AUTHORITY IDENTIFIED BY Datahuskies123;
GRANT CONNECT, RESOURCE TO AIRPORT_AUTHORITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON CUSTOMS_OFFICERS TO AIRPORT_AUTHORITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON PASSENGERS_DATA TO AIRPORT_AUTHORITY;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SYNONYM TO AIRPORT_AUTHORITY;
DISC;
CONN CUSTOMS_OFFICER/Datahuskies123;

GRANT ALL ON CUSTOMS_OFFICERS TO AIRPORT_AUTHORITY;
GRANT ALL ON PASSENGERS_DATA TO AIRPORT_AUTHORITY;

/* Uber => Tables = DRIVER_DETAILS, CAB_DETAILS */

CREATE USER UBER_SYSTEMS IDENTIFIED BY Datahuskies123;
GRANT CONNECT, RESOURCE TO UBER_SYSTEMS;
GRANT SELECT, INSERT, UPDATE, DELETE ON DRIVER_DETAILS TO UBER_SYSTEMS;
GRANT SELECT, INSERT, UPDATE, DELETE ON CAB_DETAILS TO UBER_SYSTEMS;
GRANT SELECT, INSERT, UPDATE, DELETE ON UBER_SERVICES TO UBER_SYSTEMS;
GRANT SELECT, INSERT, UPDATE, DELETE ON AIRPORT_TAXI_BOOKING_MACHINE TO UBER_SYSTEMS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SYNONYM TO UBER_SYSTEMS;
DISC;
CONN UBER_SYSTEMS/Datahuskies123;

DROP USER UBER_SYSTEMS;

GRANT ALL ON DRIVER_DETAILS TO UBER_SYSTEMS;
GRANT ALL ON CAB_DETAILS TO UBER_SYSTEMS;
GRANT ALL ON UBER_SERVICES TO UBER_SYSTEMS;
GRANT ALL ON AIRPORT_TAXI_BOOKING_MACHINE TO UBER_SYSTEMS;
/* Automatic Tables = UBER_SERVICES, AIRPORT_TAXI_BOOKING_MACHINE */

/* Passengers => AIRPORT_TAXI_BOOKING_MACHINE, PAYMENT_DETAILS */


GRANT ALL ON PAYMENT_DETAILS TO PASSENGERS;

DISC;
CONN PASSENGERS/Datahuskies123;

DROP USER UBER_SYSTEMS;

/* Cab Driver */
CREATE USER CAB_DRIVERS IDENTIFIED BY Datahuskies123;
GRANT CONNECT, RESOURCE TO CAB_DRIVERS;
GRANT SELECT, INSERT, UPDATE, DELETE ON CAB_DETAILS TO CAB_DRIVERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SYNONYM TO CAB_DRIVERS;
DISC;
CONN CAB_DRIVERS/Datahuskies123;

GRANT ALL ON CAB_DETAILS TO CAB_DRIVERS;

DROP USER CAB_DRIVERS;