/* Dropping the tables to clear the data */
DROP TABLE CUSTOMS_OFFICERS;
DROP TABLE PASSENGERS_DATA;
DROP TABLE DRIVER_DETAILS;
DROP TABLE CAB_DETAILS;
DROP TABLE UBER_SERVICES;
DROP TABLE AIRPORT_TAXI_BOOKING_MACHINE;
DROP TABLE PAYMENT_DETAILS;