/* Adding Drivers Data */
EXEC ADD_DRIVER('Allaire');

EXEC ADD_DRIVER('Babineaux');

EXEC ADD_DRIVER('Gagnon');

EXEC ADD_DRIVER('Montagne');

EXEC ADD_DRIVER('Vincent');

EXEC ADD_DRIVER('Roche');

/* Adding Cab Data */

DECLARE
    IS_DRIVER_EXIST NUMBER;
    CORRESPONDING_DRIVER_NAME VARCHAR2(60);
    CORRESPONDING_DRIVER_RATING FLOAT;
BEGIN
    ADD_CAB_TO_DATABASE('BOS-2437', 2222, IS_DRIVER_EXIST, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING, INPUT_CAB_SERVICE_NAME => 'LYFT');
END;

DECLARE
    IS_DRIVER_EXIST NUMBER;
    CORRESPONDING_DRIVER_NAME VARCHAR2(60);
    CORRESPONDING_DRIVER_RATING FLOAT;
BEGIN
    ADD_CAB_TO_DATABASE('BOS-3837', 2223, IS_DRIVER_EXIST, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING);
END;

DECLARE
    IS_DRIVER_EXIST NUMBER;
    CORRESPONDING_DRIVER_NAME VARCHAR2(60);
    CORRESPONDING_DRIVER_RATING FLOAT;
BEGIN
    ADD_CAB_TO_DATABASE('BOS-3447', 2224, IS_DRIVER_EXIST, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING, 'LYFT');
END;

DECLARE
    IS_DRIVER_EXIST NUMBER;
    CORRESPONDING_DRIVER_NAME VARCHAR2(60);
    CORRESPONDING_DRIVER_RATING FLOAT;
BEGIN
    ADD_CAB_TO_DATABASE('BOS-3431', 2225, IS_DRIVER_EXIST, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING);
END;

DECLARE
    IS_DRIVER_EXIST NUMBER;
    CORRESPONDING_DRIVER_NAME VARCHAR2(60);
    CORRESPONDING_DRIVER_RATING FLOAT;
BEGIN
    ADD_CAB_TO_DATABASE('BOS-3432', 2226, IS_DRIVER_EXIST, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING);
END;

DECLARE
    IS_DRIVER_EXIST NUMBER;
    CORRESPONDING_DRIVER_NAME VARCHAR2(60);
    CORRESPONDING_DRIVER_RATING FLOAT;
BEGIN
    ADD_CAB_TO_DATABASE('BOS-3497', 2227, IS_DRIVER_EXIST, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING, INPUT_CAB_SERVICE_NAME => 'ORANGE CABS');
END;

/* Cannot enter this data since this driver doesn't exist - error test case */
DECLARE
    IS_DRIVER_EXIST NUMBER;
    CORRESPONDING_DRIVER_NAME VARCHAR2(60);
    CORRESPONDING_DRIVER_RATING FLOAT;
BEGIN
    ADD_CAB_TO_DATABASE('BOS-3537', 2228, IS_DRIVER_EXIST, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING);
END;

/* Adding Customs Officer Data */

EXEC ADD_TO_CUSTOMS_OFFICERS('JOHN WESLEY');

EXEC ADD_TO_CUSTOMS_OFFICERS('PETER RUSSO');

EXEC ADD_TO_CUSTOMS_OFFICERS('Maria Garcia', INPUT_OFFICER_COUNTRY => 'UAE');

EXEC ADD_TO_CUSTOMS_OFFICERS('James Johnson', INPUT_OFFICER_COUNTRY => 'ENG');

EXEC ADD_TO_CUSTOMS_OFFICERS('James Smith', 'CAD');

EXEC ADD_TO_CUSTOMS_OFFICERS('BIANCO AJELLO');

/* Adding Passengers Data */

DECLARE
    PROCEDURE_OUTPUT NUMBER;
    IS_VALID_OFFICER NUMBER;
BEGIN
    ADD_TO_PASSENGERS('U1852134', 777777777777, 'STACY', 'ENG', 'RIVERWAY, BOSTON', 'I94333762', PROCEDURE_OUTPUT, IS_VALID_OFFICER);
END;

DECLARE
    PROCEDURE_OUTPUT NUMBER;
    IS_VALID_OFFICER NUMBER;
BEGIN
    ADD_TO_PASSENGERS('T1853125', 777777777789, 'PORT JANE', 'SPN', 'EVERGREEN, BOSTON', 'I94333763', PROCEDURE_OUTPUT, IS_VALID_OFFICER);
END;

DECLARE
    PROCEDURE_OUTPUT NUMBER;
    IS_VALID_OFFICER NUMBER;
BEGIN
    ADD_TO_PASSENGERS('E1852134', 777777777789, 'WADE SETH', 'FRA', 'BROOKLINE, BOSTON', 'I94333764', PROCEDURE_OUTPUT, IS_VALID_OFFICER);
END;

DECLARE
    PROCEDURE_OUTPUT NUMBER;
    IS_VALID_OFFICER NUMBER;
BEGIN
    ADD_TO_PASSENGERS('T1256167', 777777777801, 'RILEY JORGE', 'SAF', 'PLANE J., BOSTON', 'I94333765', PROCEDURE_OUTPUT, IS_VALID_OFFICER);
END;

/* Adding Payment Data */
DECLARE
    BILLING_ADDRESS VARCHAR2(60);
BEGIN
    ADD_PAYMENT_DETAILS(100000000011, 2222405343248877, BILLING_ADDRESS);
END;

DECLARE
    BILLING_ADDRESS VARCHAR2(60);
BEGIN
    ADD_PAYMENT_DETAILS(100000000012, 2222990905257051, BILLING_ADDRESS);
END;

/* Cab Returning to Airport */

EXEC CAB_IS_OPEN_TO_HIRE(1111);


