/* Adding Drivers Data */
EXEC ADD_DRIVER('Allaire');

EXEC ADD_DRIVER('Babineaux');

EXEC ADD_DRIVER('Gagnon');

EXEC ADD_DRIVER('Montagne');

EXEC ADD_DRIVER('Vincent');

EXEC ADD_DRIVER('Roche');

/* Adding Cab Data */

DECLARE
    IS_DRIVER_EXIST NUMBER;
    CORRESPONDING_DRIVER_NAME VARCHAR2(60);
    CORRESPONDING_DRIVER_RATING FLOAT;
BEGIN
    ADD_CAB_TO_DATABASE('BOS-2437', 2222, IS_DRIVER_EXIST, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING, INPUT_CAB_SERVICE_NAME => 'LYFT');
END;

DECLARE
    IS_DRIVER_EXIST NUMBER;
    CORRESPONDING_DRIVER_NAME VARCHAR2(60);
    CORRESPONDING_DRIVER_RATING FLOAT;
BEGIN
    ADD_CAB_TO_DATABASE('BOS-3837', 2223, IS_DRIVER_EXIST, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING);
END;

DECLARE
    IS_DRIVER_EXIST NUMBER;
    CORRESPONDING_DRIVER_NAME VARCHAR2(60);
    CORRESPONDING_DRIVER_RATING FLOAT;
BEGIN
    ADD_CAB_TO_DATABASE('BOS-3447', 2224, IS_DRIVER_EXIST, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING, 'LYFT');
END;

DECLARE
    IS_DRIVER_EXIST NUMBER;
    CORRESPONDING_DRIVER_NAME VARCHAR2(60);
    CORRESPONDING_DRIVER_RATING FLOAT;
BEGIN
    ADD_CAB_TO_DATABASE('BOS-3431', 2225, IS_DRIVER_EXIST, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING);
END;

DECLARE
    IS_DRIVER_EXIST NUMBER;
    CORRESPONDING_DRIVER_NAME VARCHAR2(60);
    CORRESPONDING_DRIVER_RATING FLOAT;
BEGIN
    ADD_CAB_TO_DATABASE('BOS-3432', 2226, IS_DRIVER_EXIST, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING);
END;

DECLARE
    IS_DRIVER_EXIST NUMBER;
    CORRESPONDING_DRIVER_NAME VARCHAR2(60);
    CORRESPONDING_DRIVER_RATING FLOAT;
BEGIN
    ADD_CAB_TO_DATABASE('BOS-3497', 2227, IS_DRIVER_EXIST, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING, INPUT_CAB_SERVICE_NAME => 'ORANGE CABS');
END;

/* Cannot enter this data since this driver doesn't exist - error test case */
DECLARE
    IS_DRIVER_EXIST NUMBER;
    CORRESPONDING_DRIVER_NAME VARCHAR2(60);
    CORRESPONDING_DRIVER_RATING FLOAT;
BEGIN
    ADD_CAB_TO_DATABASE('BOS-3537', 2228, IS_DRIVER_EXIST, CORRESPONDING_DRIVER_NAME, CORRESPONDING_DRIVER_RATING);
END;


